server:
  port: 80
  mode: debug # debug, release, test

database:
  host: 10.50.104.140
  port: 3306
  user: root
  password: '' # 替换为你本地 MySQL 的密码 syU7m3Bf
  dbname: miniapp
  timezone: Asia/Shanghai

wechat:
  appid: ''
  appsecret: ''
  template_id: ''

redis:
  addr: 127.0.0.1:6379
  password: ''
  db: 0
