server:
  port: 8080
  mode: debug # debug, release, test

database:
  host: 10.50.104.140
  port: 3306
  user: root
  password: 'syU7m3Bf'
  dbname: miniapp
  timezone: Asia/Shanghai

redis:
  addr: 127.0.0.1:6379
  password: ''
  db: 0
