server:
  port: 80
  mode: debug # debug, release, test

database:
  host: 10.50.104.140
  port: 3306
  user: root
  password: '888888'
  dbname: miniapp
  timezone: Asia/Shanghai

wechat:
  appid: 'YOUR_APP_ID'
  appsecret: 'YOUR_APP_SECRET'
